import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar/NavBar";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

const space = Space_Grotesk({
  weight: ["400"],
  variable: "--font-space",
  subsets: ["latin"],
});

const rodetta = localFont({
  src: "../public/fonts/rodetta.woff",
  variable: "--font-rodetta",
  display: "swap",
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space.variable} ${rodetta.variable} font-space`}>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
